# Generated by Django 3.2.7 on 2021-11-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seats', verbose_name='사진')),
                ('name', models.CharField(max_length=128, verbose_name='좌석명')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='restaurants.restaurant', verbose_name='식당')),
            ],
            options={
                'verbose_name': '좌석',
                'verbose_name_plural': '좌석',
            },
        ),
    ]
