# Generated by Django 3.2.7 on 2021-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
    ]
