# Generated by Django 3.2.7 on 2021-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(max_length=20, verbose_name='코드'),
        ),
    ]
